name: Release nuget

on:
  push:
    tags: "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release      
      
    - name: Create the package - MyTcpSockets
      run: dotnet pack --configuration Release MyTcpSockets/MyTcpSockets.csproj /p:Version=${GITHUB_REF#refs/tags/}
    - name: Create the package - MyTcpSockets20
      run: dotnet pack --configuration Release MyTcpSockets20/MyTcpSockets20.csproj /p:Version=${GITHUB_REF#refs/tags/}

    - name: Publish the package to GPR - MyTcpSockets
      run: dotnet nuget push MyTcpSockets/bin/Release/*.nupkg -s "https://api.nuget.org/v3/index.json" -k ${{ secrets.NUGET_TOCKEN }}
    - name: Publish the package to GPR - MyTcpSockets20
      run: dotnet nuget push MyTcpSockets20/bin/Release/*.nupkg -s "https://api.nuget.org/v3/index.json" -k ${{ secrets.NUGET_TOCKEN }}

      
